### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-primero#25]
(node:19759) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

See recent run: https://www.openfn.org/projects/p5am6e/runs/rrkz3r3g

**Comment by lakhassane** [comment]
Solved with Taylor's PR.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane Still seeing this on prod... maybe not deployed? 
https://www.openfn.org/projects/p5kaap/runs/rk5g3r45

**Comment by lakhassane** [comment]
yes @aleksa-krolls. Will release today.
